language: objective-c
osx_image: xcode8
xcode_project: BlackMusicCenter.xcworkspace
xcode_scheme: BlackMusicCenter
bundler_args: --retry 5
branches:
  only:
    - develop
    - master
notifications:
  email: false
before_install:
  - gem install bundle
  - bundle install && brew bundle
  - pod install
script:
  - bundle exec fastlane blackmusiccenter
