default_platform :ios

lane :blackmusiccenter do
  cocoapods
  scan(
    scheme: 'BlackMusicCenter',
    devices: ["iPhone SE"],
    code_coverage: true,
    clean: true,
    output_types: "html"
  )
  xcov(
    workspace: "BlackMusicCenter.xcworkspace",
    scheme: "BlackMusicCenter",
    output_directory: "fastlane/xcov_output"
  )
end
